branches:
  only:
  - hydro-devel
matrix:
  allow_failures:
  - compiler: clang
notifications:
  email:
  - rick1987@gmail.com
env:
  global:
script: ./.travis/build
before_install: ./.travis/before_install
language: cpp
compiler:
- clang
- gcc
after_success:: ./.travis/after_success
