/* Auto-generated by genmsg_cpp for file /home/huier/Downloads/catkin_ws/src/pf_example/msg/RangeMeasurement.msg */
#ifndef PF_EXAMPLE_MESSAGE_RANGEMEASUREMENT_H
#define PF_EXAMPLE_MESSAGE_RANGEMEASUREMENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace pf_example
{
template <class ContainerAllocator>
struct RangeMeasurement_ {
  typedef RangeMeasurement_<ContainerAllocator> Type;

  RangeMeasurement_()
  : header()
  , value(0.0)
  {
  }

  RangeMeasurement_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , value(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _value_type;
  float value;


  typedef boost::shared_ptr< ::pf_example::RangeMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pf_example::RangeMeasurement_<ContainerAllocator>  const> ConstPtr;
}; // struct RangeMeasurement
typedef  ::pf_example::RangeMeasurement_<std::allocator<void> > RangeMeasurement;

typedef boost::shared_ptr< ::pf_example::RangeMeasurement> RangeMeasurementPtr;
typedef boost::shared_ptr< ::pf_example::RangeMeasurement const> RangeMeasurementConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pf_example::RangeMeasurement_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pf_example::RangeMeasurement_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pf_example

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pf_example::RangeMeasurement_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pf_example::RangeMeasurement_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pf_example::RangeMeasurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4bea522f9243fd34ea7bc74ce85697a8";
  }

  static const char* value(const  ::pf_example::RangeMeasurement_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4bea522f9243fd34ULL;
  static const uint64_t static_value2 = 0xea7bc74ce85697a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pf_example::RangeMeasurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pf_example/RangeMeasurement";
  }

  static const char* value(const  ::pf_example::RangeMeasurement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pf_example::RangeMeasurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::pf_example::RangeMeasurement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pf_example::RangeMeasurement_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pf_example::RangeMeasurement_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pf_example::RangeMeasurement_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct RangeMeasurement_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pf_example::RangeMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pf_example::RangeMeasurement_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PF_EXAMPLE_MESSAGE_RANGEMEASUREMENT_H

